[[SCS_GPU]]
arch = "x86_64"
git-tree-sha1 = "75af8ea51c3700c8dd08e7a1a472fe2472765182"
libc = "glibc"
os = "linux"

    [[SCS_GPU.download]]
    sha256 = "234a4bb3de9d8b6c1aaf8d923ae17475bb41ee1c0c6d88929509bbd8b3352492"
    url = "https://github.com/kalmarek/SCS_GPU_jll.jl/releases/download/SCS_GPU-v2.1.2+0/SCS_GPU.v2.1.2.x86_64-linux-gnu.tar.gz"
